# Generated by Django 4.2.7 on 2023-11-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
