# Generated by Django 4.1.12 on 2023-11-23 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9)]),
        ),
    ]
